### ISSUE TITLE
Error in error_deff @ top energy

### ISSUE THREAD

**Issue by anagtv** [pylhc/Beta-Beat.src#101]
I have just found that the file /afs/cern.ch/work/o/omc/Error_definition_files/6500GeV has only 0 values (error_deff.txt). So, when doing analysis for single measurement using N-BPM metod, the getbeta_ files contain only nan in the beta and errorbeta columns and the getampbeta_ files contain nan in the betres and betresstd columns.
Also the output log is full with errors like this. 
beti = float(np.dot(np.transpose(w), betas) / VBeta_inv_sum)
/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/GetLLM/algorithms/beta.py:1532: RuntimeWarning: invalid value encountered in divide.
For 3BPM method or analysing several files everything works fine.

**Comment by jaimecp89** [comment]
When this is fixed I will remove the write access to this directory of everyone. It is extremelly easy to do something like "vim err_deff.txt" (not noticing that its a link to the OMC files) and mess it up.

**Comment by rogeliotomas** [comment]
hi,this must have been a wrong copy of andy's files. Has this been fixed?ciaorogelio 
-------- Message d'origine --------De : anagtv <notifications@github.com> Date : 15.03.18  11:52 AM  (GMT+01:00) À : "pylhc/Beta-Beat.src" <Beta-Beat.src@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [pylhc/Beta-Beat.src] Error in error_deff @ top energy (#101) 
I have just found that the file /afs/cern.ch/work/o/omc/Error_definition_files/6500GeV has only 0 values (error_deff.txt). So, when doing analysis for single measurement using N-BPM metod, the getbeta_ files contain only nan in the beta and errorbeta columns and the getampbeta_ files contain nan in the betres and betresstd columns.

Also the output log is full with errors like this.

beti = float(np.dot(np.transpose(w), betas) / VBeta_inv_sum)

/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/GetLLM/algorithms/beta.py:1532: RuntimeWarning: invalid value encountered in divide.

For 3BPM method or analysing several files everything works fine.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pylhc/Beta-Beat.src","title":"pylhc/Beta-Beat.src","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pylhc/Beta-Beat.src"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Error in error_deff @ top energy (#101)"}],"action":{"name":"View Issue","url":"https://github.com/pylhc/Beta-Beat.src/issues/101"}}}

**Comment by jaimecp89** [comment]
@awegsche confirms that the file is now fine.
