### ISSUE TITLE
tfs_pandas header parser for multi-word headers

### ISSUE THREAD

**Issue by JoschD** [pylhc/Beta-Beat.src#123]
I got tfs files, e.g. error tables, that have headers with more than one word as names (see below).
These can not be read by tfs_pandas as it assumes that the third part (split by spaces) is already the data-type (hence it raises TfsFormatError).

Hence, maybe join all parts until one starts with % ?

------------------------------------- Example Header -------------------------------------

@ Error sources            %20s "MAGNETIC_FIELD,POWER"
@ Magnet types             %102s "MB,MBRB,MBRC,MBRS,MBW,MBX,MBXW,MQ,MQM,MQMC,MQML,MQS,MQSX,MQT,MQTLH,MQTLI,MQWA,MQWB,MQXA,MQXB,MQY,OTHER"
@ Multipoles               %69s "a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11"
@ s (m)                    %3s "ALL"
@ Sectors                  %3s "ALL"
@ Options                  %32s "FIDEL-DYNAMIC-MODEL,B2-CLOCKWISE"
@ Conventions              %178s "Multipoles for both beams expressed in local measurement ref frame, s-axis: CS->NCS, x-axis: horisontal, right-hand axis when looking in CS->NCS direction, y-axis: up in sky (-g)"
@ Cycle state              %16s "FLAT-TOP SQUEEZE"
@ Squeeze state of IPs with matched optics
@ Beta IP1 (m)             %le 0.40
@ Beta IP2 (m)             %le 10.00
@ Beta IP5 (m)             %le 0.40
@ Beta IP8 (m)             %le 3.00
@ Previous cycle           %9s "PRE-CYCLE"
@ Energy (TeV)             %le 6.500
@ Charge (e)               %le 1
@ FiDeL model parameters updated  %08s    01/07/14
@ LHC slot allocation updated  %08s    01/06/14

**Comment by JoschD** [comment]
Question: Should it be allowed to have just comments in the header, like (see above):
_@ Squeeze state of IPs with matched optics_

??

**Comment by awegsche** [comment]
A few comments on that:

- for multiword parameters you could use replacement characters for 
whitespaces (like underscore)
- for comments, there is the possibility
@ comment %s "actual comment"
or use another comment character (#, //, !)

Also the important phase advance would profit from multiword headers 
because the header would be
Element1 to Element2 using BPM1 and BPM2 %s "delta +- error; delta_deg 
+- error_deg"
which at the moment I avoid by using double underscores (because one 
alone can appear in the BPM name)
Element1__to__Element2__using__BPM1__and__BPM2 %s "delta +- error; 
delta_deg +- error_deg"

**Comment by JoschD** [comment]
@awegsche no need for underscores any more, you can use spaces.

I close this issue with the hint to Andreas solution to identify comments as such by e.g. 
__@ comment %s "Comment"__
